In [1]:
import pandas as pd
import numpy as np

### Q1. What version of Pandas did you install?

In [2]:
print(pd.__version__)

2.2.3


## Loading the data

In [3]:
fuel_efficiency_url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

df_fuel = pd.read_csv(filepath_or_buffer=fuel_efficiency_url)

df_fuel.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count

How many records are in the dataset?

In [4]:
df_fuel.shape[0]

9704

### Q3. Fuel types

How many fuel types are presented in the dataset?

In [5]:
n_unique_fuel_type = df_fuel['fuel_type'].nunique()
print(f"There is a total of {n_unique_fuel_type} unique fuel types")

df_fuel['fuel_type'].value_counts()

There is a total of 2 unique fuel types


fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

## Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [6]:
cols_with_missing_values = (
    df_fuel.isnull()
           .sum()
           .sort_values(ascending=False)
           .pipe(lambda x: x[x > 0])
)

print(f"There is a total of {len(cols_with_missing_values)} columns with missing values: {cols_with_missing_values.index.tolist()}")

cols_with_missing_values

There is a total of 4 columns with missing values: ['acceleration', 'horsepower', 'num_doors', 'num_cylinders']


acceleration     930
horsepower       708
num_doors        502
num_cylinders    482
dtype: int64

### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [7]:
df_fuel[df_fuel['origin'] == 'Asia'] ['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

### Q6. Median value of horsepower

1. Find the median value of the `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

1. Find the median value of the `horsepower` column in the dataset.

In [8]:
hp_median = df_fuel['horsepower'].median()

hp_median

np.float64(149.0)

2. Next, calculate the most frequent value of the same `horsepower` column.

In [9]:
hp_most_frequent = df_fuel['horsepower'].mode()[0]

hp_most_frequent

np.float64(152.0)

3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.

In [10]:
hp_mode_imputing = df_fuel['horsepower'].fillna(hp_most_frequent)

hp_mode_imputing.isnull().sum()

np.int64(0)

4. Now, calculate the median value of `horsepower` once again.

In [11]:
hp_mode_imputing.median()

np.float64(152.0)

Has the median changed?

- Yes, it's value increased after applying mode imputation. The median is now the same as the mode.

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

1. Select all the cars from Asia

In [12]:
df_asia = df_fuel[df_fuel['origin'] == 'Asia']

df_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

2. Select only columns `vehicle_weight` and `model_year`

In [13]:
df_asia_subset = df_asia[['vehicle_weight', 'model_year']]

df_asia_subset

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

3. Select the first 7 values

In [14]:
df_first_seven = df_asia_subset.head(7)

4. Get the underlying NumPy array. Let's call it `X`.

In [15]:
X = df_first_seven.values

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [16]:
XTX = X.T @ X

XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

6. Invert `XTX`.

In [17]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [19]:
w = XTX_inv @ X.T @ y

w

array([0.01386421, 0.5049067 ])

9. What's the sum of all the elements of the result?

In [20]:
sum(w)

np.float64(0.5187709081074016)

The sum of the weights is `0.51`.